const actions = {
  main: {
    START_RECORDING_REQUESTED: 'START_RECORDING_REQUESTED',
    GET_STORE_VALUE: 'GET_STORE_VALUE',
    SET_STORE_VALUE: 'SET_STORE_VALUE',
    CHANGE_AUDIO_REQUESTED: 'CHANGE_AUDIO_REQUESTED',
    CHANGE_CAMERA_REQUESTED: 'CHANGE_CAMERA_REQUESTED',
    CHANGE_SCREEN_REQUESTED: 'CHANGE_SCREEN_REQUESTED',
    GET_SCREEN_INPUTS: 'GET_SCREEN_INPUTS',
    STOP_RECORDING_REQUESTED: 'STOP_RECORDING_REQUESTED',
    GET_APP_PATHS: 'GET_APP_PATHS',
    GET_APP_PERMISSIONS: 'GET_APP_PERMISSIONS',
    REQUEST_GRANT_PERMISSION: 'REQUEST_GRANT_PERMISSION'

  },
  renderer: {
    START_RECORDING: 'START_RECORDING',
    CHANGE_AUDIO: 'CHANGE_AUDIO',
    CHANGE_CAMERA: 'CHANGE_CAMERA',
    CHANGE_SCREEN: 'CHANGE_SCREEN',
    SET_SCREEN_SOURCES: 'SET_SCREEN_SOURCES',
    STOP_RECORDING: 'STOP_RECORDING',
    SET_APP_PATHS: 'SET_APP_PATHS',
    SET_APP_PERMISSIONS: 'SET_APP_PERMISSIONS'
  }
}

module.exports = {actions}